let socket=null,meuNome=null,voltando=false,reconexao=false;const TOKEN_KEY="noiteDeJogosToken",el=id=>document.getElementById(id),mostrar=(id,sim)=>el(id).classList.toggle("hidden",!sim);
function enviar(d){if(socket&&socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify(d))}
function conectar(){if(voltando||(socket&&socket.readyState<=WebSocket.OPEN))return;const p=location.protocol==="https:"?"wss":"ws";socket=new WebSocket(`${p}://${location.host}/ws/jogos/mais-provavel`);socket.onopen=()=>{const token=localStorage.getItem(TOKEN_KEY);el("status").textContent="Recuperando sua sessão...";if(token)enviar({acao:"reconectar",token});else{mostrar("entrada",true);el("status").textContent="Use seu código de recuperação."}};socket.onmessage=e=>processar(JSON.parse(e.data));socket.onclose=()=>{socket=null;if(voltando||reconexao)return;el("status").textContent="Conexão perdida. Reconectando...";reconexao=true;setTimeout(()=>{reconexao=false;conectar()},2000)}}
function processar(d){if(d.tipo==="erro")return alert(d.mensagem);if(d.tipo==="sessao"){localStorage.setItem(TOKEN_KEY,d.token);meuNome=d.nome;el("status").textContent=`Conectado como ${meuNome}`;mostrar("entrada",false);return}if(d.tipo==="sessao_invalida"){localStorage.removeItem(TOKEN_KEY);mostrar("entrada",true);el("status").textContent="Sessão antiga não encontrada.";return}if(d.tipo==="voltar_lobby"){voltando=true;if(socket){socket.onclose=null;socket.close()}location.href="/";return}if(d.tipo==="estado")renderizar(d)}
function lista(container,jogadores,campo){container.replaceChildren(...[...jogadores].sort((a,b)=>b[campo]-a[campo]).map(j=>{const linha=document.createElement("div");linha.className=`linha${j.conectado?"":" offline"}`;const nome=document.createElement("strong");nome.textContent=`${j.nome}${j.host?" · HOST":""}`;const valor=document.createElement("span");valor.textContent=`${j[campo]} voto${j[campo]===1?"":"s"}`;linha.append(nome,valor);return linha}))}
function opcoes(d){el("opcoes").replaceChildren(...d.jogadores.filter(j=>d.fase==="resultado"?j.votos_rodada>0:true).map(j=>{const botao=document.createElement("button");botao.className="opcao";botao.disabled=d.ja_votei||d.fase!=="votando";if(j.id===d.meu_voto)botao.classList.add("selecionada");botao.textContent=d.fase==="resultado"?`${j.nome}: ${j.votos_rodada} voto${j.votos_rodada===1?"":"s"}`:j.nome;botao.onclick=()=>enviar({acao:"votar",jogador_id:j.id});return botao}))}
function chips(d){el("statusVotos").replaceChildren(...d.jogadores.map(j=>{const chip=document.createElement("span");chip.className=`chip${j.votou?" votou":""}`;chip.textContent=`${j.nome}: ${j.votou?"votou":"pensando"}`;return chip}))}
function renderizar(d){if(!d.jogadores.some(j=>j.nome===meuNome))return;el("meuCodigo").textContent=d.codigo_recuperacao||"----";mostrar("sala",!d.jogo_iniciado&&!d.jogo_finalizado);mostrar("partida",d.jogo_iniciado);mostrar("final",d.jogo_finalizado);mostrar("voltar",d.sou_host);lista(el("jogadoresSala"),d.jogadores,"total_votos");mostrar("configuracao",d.sou_host);mostrar("aguarde",!d.sou_host);if(d.jogo_iniciado){el("progresso").textContent=`${d.numero_rodada}/${d.quantidade_rodadas}`;el("fase").textContent=d.fase==="votando"?"Votando":"Resultado";el("situacao").textContent=d.situacao;opcoes(d);chips(d);mostrar("resultadoRodada",d.fase==="resultado");if(d.fase==="resultado")lista(el("contagem"),d.jogadores,"votos_rodada");mostrar("encerrar",d.sou_host&&d.fase==="votando");mostrar("proxima",d.sou_host&&d.fase==="resultado");el("proxima").textContent=d.ultima_rodada?"Ver resultado final":"Próxima situação";el("mensagem").textContent=d.fase==="votando"?(d.ja_votei?"Voto registrado. Aguarde os demais.":"Escolha um jogador."):"Os votos desta rodada foram revelados."}if(d.jogo_finalizado){const empate=d.destaques.length>1;el("destaque").textContent=empate?`👉 Empate entre ${d.destaques.join(", ")} com ${d.maior_total} votos!`:`👉 ${d.destaques[0]} foi o mais votado, com ${d.maior_total} votos!`;lista(el("ranking"),d.jogadores,"total_votos");mostrar("nova",d.sou_host)}}
function recuperar(){enviar({acao:"recuperar_codigo",codigo:el("codigo").value.trim()})}function comecar(){enviar({acao:"comecar",quantidade:parseInt(el("quantidade").value,10)})}function encerrar(){enviar({acao:"encerrar_votacao"})}function proxima(){enviar({acao:"proxima"})}function novaPartida(){enviar({acao:"nova_partida"})}function voltarLobby(){enviar({acao:"voltar_lobby"})}el("codigo").addEventListener("keydown",e=>{if(e.key==="Enter")recuperar()});conectar();
